[package]
name = "chapter03_one_player_game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_mt = "4.2.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
